[build]
  publish = "dist"

[functions]
  directory = "netlify/functions"

[dev]
  targetPort = 3000

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200
  force = true